package com.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "header")
@XmlAccessorType(XmlAccessType.FIELD)
public class Header {

	/**
	 * (mandatory) This will be a fix value 'COAPI'. Incase any other value(not in
	 * list) passed then error will be displayed " Invalid Channel Id".(String 10)
	 */
	@XmlElement(name = "extsysname", required = true)
	public String extsysname;

	/**
	 * (mandatory) datpost(yyyy-mm-dd) field received in Request XML from third
	 * party system cannot be future date.
	 */
	@XmlElement(name = "datpost", required = true)
	private String datpost;

	/**
	 * (mandatory) Batch number generated by external system.(String 6)
	 */
	@XmlElement(name = "batchnumext", required = true)
	private String batchnumext;

	/**
	 * (mandatory) Fix value CO_BD2 will be received.(String 10)
	 */
	@XmlElement(name = "idtxn", required = true)
	private String idtxn;

	/**
	 * (mandatory) Fixed value 'INR'.(String 3)
	 */
	@XmlElement(name = "codcurr", required = true)
	private String codcurr;

	/**
	 * (mandatory) Will be validated from FC@C user id's and should be part of
	 * requested group id. Incase user id not found then request will be rejected
	 * with proper error message.(String 16)
	 */
	@XmlElement(name = "iduser", required = true)
	private String iduser;

	/**
	 * (mandatory) Customer Id.(String 9)
	 */
	@XmlElement(name = "idcust", required = true)
	private String idcust;

	/**
	 * (not-mandatory) This should be valid FC@C Group id.(String 20)
	 */
	@XmlElement(name = "groupid", required = true)
	private String groupid;

	/**
	 * (not-mandatory) Request time stamp,DATE(YYYY-MM-DDTHH24:MM:SS).
	 */
	@XmlElement(name = "reqdatetime", required = true)
	private String reqdatetime;

	public String getExtsysname() {
		return extsysname;
	}

	public void setExtsysname(String extsysname) {
		this.extsysname = extsysname;
	}

	public String getDatpost() {
		return datpost;
	}

	public void setDatpost(String datpost) {
		this.datpost = datpost;
	}

	public String getBatchnumext() {
		return batchnumext;
	}

	public void setBatchnumext(String batchnumext) {
		this.batchnumext = batchnumext;
	}

	public String getIdtxn() {
		return idtxn;
	}

	public void setIdtxn(String idtxn) {
		this.idtxn = idtxn;
	}

	public String getCodcurr() {
		return codcurr;
	}

	public void setCodcurr(String codcurr) {
		this.codcurr = codcurr;
	}

	public String getIduser() {
		return iduser;
	}

	public void setIduser(String iduser) {
		this.iduser = iduser;
	}

	public String getIdcust() {
		return idcust;
	}

	public void setIdcust(String idcust) {
		this.idcust = idcust;
	}

	public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getReqdatetime() {
		return reqdatetime;
	}

	public void setReqdatetime(String reqdatetime) {
		this.reqdatetime = reqdatetime;
	}

	@Override
	public String toString() {
		return "header [extsysname=" + extsysname + ", datpost=" + datpost + ", batchnumext=" + batchnumext + ", idtxn="
				+ idtxn + ", codcurr=" + codcurr + ", iduser=" + iduser + ", idcust=" + idcust + ", groupid=" + groupid
				+ ", reqdatetime=" + reqdatetime + "]";
	}

}
